config/routes.rb
Rails.application.routes.draw do
  resources :categories
post "packages/:id/bundles/:id/edit"    => "bundles#edit" 

  resources :bundles
  resources :frequencies
  resources :packages 
  resource :session
  get 'signup' => 'users#new'
  resources :users
  resources :products 
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
end

app/models/bundle.rb
class Bundle < ActiveRecord::Base
  belongs_to :package
  belongs_to :product
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :characterizations, dependent: :destroy
    has_many :products, through: :characterizations
    has_many :packages, through: :characterizations 
end

app/models/characterization.rb
class Characterization < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
  belongs_to :package
end

app/models/frequency.rb
class Frequency < ActiveRecord::Base
  belongs_to :product
  belongs_to :package
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  
  
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :package
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  
  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    (unit_price-((((0.025*(quantity*quantity))+(0.25*quantity))/100)*unit_price))*quantity
  end
  
  def undis_total_price
    unit_price*quantity
  end


private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end


  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = total_price
    self[:undis_total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/package.rb
class Package < ActiveRecord::Base
has_many :order_items
has_many :bundles, dependent: :destroy
has_many :products, through: :bundles
has_many :characterizations, dependent: :destroy
has_many :categories, through: :characterizations
    
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  has_many :order_items
  has_many :bundles, dependent: :destroy
  has_many :packages, through: :bundles
  has_many :characterizations, dependent: :destroy
  has_many :categories, through: :characterizations

  default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders, dependent: :destroy
  has_secure_password
  
    def self.authenticate(email, password)
        user = User.find_by(email: email)
        user && user.authenticate(password)
    end
end

app/controllers/bundles_controller.rb
class BundlesController < ApplicationController
    def index
        @package = Package.find(params[:package_id])
        @bundles = Bundle.where(package_id: @package.id)
    end
    
    def show
        @bundle = Bundle.find(params[:id])
    end
    
    def edit
     @bundle = Bundle.find(params[:id])
    end
    
   
    def update
      @bundle = Bundle.find(params[:id])
     @package = @bundle.package_id
      if @bundle.update(bundle_params)
          @product = @bundle.product_id
          @productprice = Product.find_by(id: @product).price
         @bundle.bundleprice = @bundle.amount * @productprice
         @bundle.update(bundle_params)
         @thepackage = Package.find_by(id: @package)
         @packprice =  @thepackage.bundles.sum(:bundleprice)
         @thepackage.packageprice = @packprice 
         @thepackage.save 
            
         
        @redirect = @bundle.package.id
        redirect_to package_path(@redirect), notice: "Account successfully updated!"
      else
        render :edit
      end
    end

    private

    def bundle_params
        params.require(:bundle).permit(:amount)
    end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    #@order = current_order
    #@order_items = @order.order_items
    @user = User.find(session[:user_id])
    @orders = @user.orders 
    @order = @orders.find_by_order_status_id(1)
    @order_items = @order.order_items
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
  
  def new
    @product = Product.new
  end 
  
  def show
    @product = Product.find(params[:id])
    @order_item = current_order.order_items.new
  end
  
  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to products_path
  end
  
  
   private

    def product_params
        params.require(:product).permit(:name, :price, category_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end
    
    def show
         @user = User.find(params[:id])
         @order = Order.find_by(params[:user_id])
        
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            @order = Order.new(user_id: @user.id)
            @order.save
            session[:user_id] = @user.id
            redirect_to @user, notice: "Thanks for signing up!"
        else
            render :new
        end 
    end

private

    def user_params
        params.require(:user).
        permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
      User.find(session[:user_id]) if session[:user_id]
    end

end

app/helpers/bundle_helper.rb
module BundleHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/frequencies_helper.rb
module FrequenciesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>s
    </div>
    
  </div>
</div>

app/views/products/index.html.erb
<h1>Products#index</h1>


<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>create new product</h1>

<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %> <br/> 
  </p>
  <p>
    <%= f.label :price %> <br/>
    <%= f.text_field :price %> <br/> 
  </p>
  <li>
  <%= f.collection_check_boxes(:package_ids, Package.all, :id, :name) %>
  </li>
  <li>
  <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
  </li>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/show.html.erb
<h1> <%= @product.name %></h1>


<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= @product.name %></small></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for @order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency @product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: @product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>s
    </div>
    
  </div>
</div>

<html>
  <head>
    <style>
      #map {
        height: 400px;
        width: 100%;
       }
    </style>
  </head>
  <body>
    <h3><%= @product.name %></h3>
    <div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: <%= @product.latitude %>, lng: <%= @product.longitude %>}; 
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD9zuVfHwSuID8e1KgB7MiUkbvl8JzMaAc&callback=initMap">
    </script>
  </body>
</html>
    