config/routes.rb
Rails.application.routes.draw do
  resources :categories
post "packages/:id/bundles/:id/edit"    => "bundles#edit" 

  resources :bundles
  resources :frequencies
  resources :packages 
  resource :session
  get 'signup' => 'users#new'
  resources :users
  resources :products 
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
end

app/models/bundle.rb
class Bundle < ActiveRecord::Base
  belongs_to :package
  belongs_to :product
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :characterizations, dependent: :destroy
    has_many :products, through: :characterizations
    has_many :packages, through: :characterizations 
end

app/models/characterization.rb
class Characterization < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
  belongs_to :package
end

app/models/frequency.rb
class Frequency < ActiveRecord::Base
  belongs_to :product
  belongs_to :package
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  
  
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :package
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  
  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    (unit_price-((((0.025*(quantity*quantity))+(0.25*quantity))/100)*unit_price))*quantity
  end
  
  def undis_total_price
    unit_price*quantity
  end


private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end


  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = total_price
    self[:undis_total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/package.rb
class Package < ActiveRecord::Base
has_many :order_items
has_many :bundles, dependent: :destroy
has_many :products, through: :bundles
has_many :characterizations, dependent: :destroy
has_many :categories, through: :characterizations
    
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  has_many :order_items
  has_many :bundles, dependent: :destroy
  has_many :packages, through: :bundles
  has_many :characterizations, dependent: :destroy
  has_many :categories, through: :characterizations

  default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders, dependent: :destroy
  has_secure_password
  
    def self.authenticate(email, password)
        user = User.find_by(email: email)
        user && user.authenticate(password)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    #@order = current_order
    #@order_items = @order.order_items
    @user = User.find(session[:user_id])
    @orders = @user.orders 
    @order = @orders.find_by_order_status_id(1)
    @order_items = @order.order_items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
      User.find(session[:user_id]) if session[:user_id]
    end

end

app/helpers/bundle_helper.rb
module BundleHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/frequencies_helper.rb
module FrequenciesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingCartExample</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %> 
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>

<%= render "shared/navbar" %>

<body>
  
 
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  

 <div class="container">
    <%= yield %>  
  </div>
</body>

</html>

app/views/shared/_navbar.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a > <%= link_to "My life", root_path, class: "navbar-brand" %></a> 
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Create <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "list product", new_product_path %></li>
                    <li><%= link_to"create package", new_package_path %></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.name %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">My subscriptions</a></li>
                    <li><a href="#">Wishlist</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Edit profile</a></li>
                    <li><a href="#">Account settings</a></li>
                    <li> <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %></li>
                  </ul>
                </li>
                <li  class="cart-text"><%= render 'layouts/cart_text'%></li>
            <% else %>
                <li><%= link_to 'Sign Up', signup_path, class: 'button' %></li>
                <li><%= link_to 'Sign In', new_session_path, class: 'button' %></li>
             <% end %>
          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to("all products", products_path) %> </li>
            <li> <%= link_to("all packages", packages_path) %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    